"""fix editor_draft updated_at type and add timestamps to rag models

Revision ID: c879fed451ce
Revises: 66c2a73ad7e7
Create Date: 2026-03-19 21:05:44.513611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c879fed451ce'
down_revision: Union[str, Sequence[str], None] = '66c2a73ad7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_summaries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('doc_summaries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('editor_drafts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # editor_drafts.updated_at: VARCHAR -> TIMESTAMP 需要分步处理
    # 1) 先去掉旧的字符串 default  2) 改类型  3) 设正确的 default
    op.execute("ALTER TABLE editor_drafts ALTER COLUMN updated_at DROP DEFAULT")
    op.execute(
        "ALTER TABLE editor_drafts ALTER COLUMN updated_at "
        "TYPE TIMESTAMP WITHOUT TIME ZONE USING updated_at::timestamp without time zone"
    )
    op.execute("ALTER TABLE editor_drafts ALTER COLUMN updated_at SET DEFAULT now()")
    op.add_column('equations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('equations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('figures', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('figures', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('paragraphs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('paragraphs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('references', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('references', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('section_headings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('section_headings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tables', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tables', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'updated_at')
    op.drop_column('tables', 'created_at')
    op.drop_column('section_headings', 'updated_at')
    op.drop_column('section_headings', 'created_at')
    op.drop_column('references', 'updated_at')
    op.drop_column('references', 'created_at')
    op.drop_column('paragraphs', 'updated_at')
    op.drop_column('paragraphs', 'created_at')
    op.drop_column('figures', 'updated_at')
    op.drop_column('figures', 'created_at')
    op.drop_column('equations', 'updated_at')
    op.drop_column('equations', 'created_at')
    op.alter_column('editor_drafts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'now()'::character varying"))
    op.drop_column('editor_drafts', 'created_at')
    op.drop_column('doc_summaries', 'updated_at')
    op.drop_column('doc_summaries', 'created_at')
    # ### end Alembic commands ###
